In [1]:
#Importing necessary libraries

import selenium
from selenium import webdriver
import pandas as pd 
import numpy as np

from selenium.webdriver.common.by import By
from selenium.common.exceptions import StaleElementReferenceException,WebDriverException, ElementClickInterceptedException, TimeoutException,ElementNotInteractableException,NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys

import requests
from bs4 import BeautifulSoup as bs

import time
from IPython.display import HTML

import warnings 
warnings.filterwarnings("ignore")

In [12]:
# Q1 Solution:

# defining the lists to be used.
ranks=[]
names=[]
artists=[]
upload_date=[]
views=[]

# defining the function for getting the target data.
def YT_Most_Viewed(url):
    
    # opening the target website.
    driver.get(url)
    time.sleep(1)
    
    # using the explicit wait method till the data-table is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']")))
    # finding the webelement for the table and getting the text data.
    data = driver.find_element(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']").text
    
    components= data.split("\n")    # splitting the text data based on newline character.
    count=1
    
    for i in components[2:]:
        if i==components[-1]:
            pass
        else:
            ranks.append(i.split('"')[0].strip()) 
            names.append(i.split('"')[1].strip())
            
            # getting the data of artists using X-Path and try-except blocks.
            try:
                artist_data=driver.find_element(By.XPATH,f'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr[{count}]/td[3]/a')
                artists.append(artist_data.text)
            except NoSuchElementException:
                artist_data=driver.find_element(By.XPATH,f'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr[{count}]/td[3]')
                artists.append(artist_data.text)
                
            # getting the views data using X-Path.
            views_data=driver.find_element(By.XPATH,f'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr[{count}]/td[4]')
            views.append(views_data.text)

            # getting the upload-dates using X-Path.
            date_data=driver.find_element(By.XPATH,f'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr[{count}]/td[5]')
            upload_date.append(date_data.text)
            count+=1

    # the final dataframe.
    results= pd.DataFrame({"Rank":ranks,
                            "Name":names, 
                            "Artist/Uploader":artists, 
                            "Upload Date":upload_date, 
                            "Views(billions)":views
                          })
    return results


driver= webdriver.Chrome("chromedriver.exe")     # connecting to the webdriver.
url="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"      # mentioning the url to scrape data from. 
df= YT_Most_Viewed(url)    # calling the function and saving the final dataframe.

driver.close()    # closing the webdriver.
df

,Rank,Name,Artist/Uploader,Upload Date,Views(billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.09
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.94
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.41
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.78
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.59
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",5.55
6,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.79
7,8.,Uptown Funk,Mark Ronson,"November 19, 2014",4.65
8,9.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.60
9,10.,Gangnam Style,Psy,"July 15, 2012",4.51
10,11.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.50
11,12.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",4.25
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",4.01
13,14.,Sugar,Maroon 5,"January 14, 2015",3.74
14,15.,Roar,Katy Perry,"September 5, 2013",3.63
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.62
16,17.,Sorry,Justin Bieber,"October 22, 2015",3.57
17,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.48
18,19.,Axel F,Crazy Frog,"June 16, 2009",3.46
19,20.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.32
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.32
21,22.,Faded,Alan Walker,"December 3, 2015",3.32
22,23.,Girls Like You,Maroon 5,"May 31, 2018",3.32
23,24.,Let Her Go,Passenger,"July 25, 2012",3.27
24,25.,Bailando,Enrique Iglesias,"April 11, 2014",3.25
25,26.,Lean On,Major Lazer,"March 22, 2015",3.24
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.22
27,28.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.21
28,29.,Shake It Off,Taylor Swift,"August 18, 2014",3.19
29,30.,Mi Gente,J Balvin,"June 29, 2017",3.12

In [3]:
# Q2 Solution:

# defining the lists to be used.
titles=[]
series=[]
venues=[]
date=[]
time_=[]

# defining the function for getting the target data.
def TeamIndia_Fixtures(url):
    
    r= requests.get(url)     # sending request to the target website.
    soup= bs(r.content)      # getting the parsed content from which we will extract our data. 
    
    # getting the link for the page containing the fixtures data.
    data= soup.find("div",id="navigation")
    link= data.find("a",class_="nav-link",href=True)

    driver.get(link['href'])    # connecting to the target page.
    time.sleep(2)

    # using the explicit wait method till the fixture cards are loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"//div[@class='fixture-card-top']")))
    # finding the webelements with fixtures data.
    data= driver.find_elements(By.XPATH,"//div[@class='fixture-card-top']")    
    for i in data:
        components=i.text.split("\n")       # processing and appending the relevant data into respective lists.
        series.append(components[0])
        date.append(components[1])
        time_.append(components[2])
    
    # finding the webelements with fixtures data. 
    data= driver.find_elements(By.XPATH,"//div[@class='fixture-card-bottom']")
    for i in data:
        components=i.text.split("\n")                       # processing and appending the relevant data into respective lists.
        titles.append(components[0].split("-")[0].strip())
        venues.append(components[0].split("-")[1].strip())

    # the final dataframe.
    results= pd.DataFrame({"Match Title":titles,
                           "Series":series, 
                           "Place":venues, 
                           "Date":date, 
                           "Time":time_
                           })
    return results

url="https://www.bcci.tv/"                       # mentioning the url to scrap data from.
driver= webdriver.Chrome("chromedriver.exe")     # connecting to the webdriver.
df= TeamIndia_Fixtures(url)                      # calling the function and saving the final dataframe.

driver.close()     # closing the webdriver.
df

,Match Title,Series,Place,Date,Time
0,1st ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare",18 AUG 2022,12:45 PM IST
1,2nd ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare",20 AUG 2022,12:45 PM IST
2,3rd ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare",22 AUG 2022,12:45 PM IST
3,1st T20I,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai",28 AUG 2022,7:30 PM IST
4,2nd T20I,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai",31 AUG 2022,7:30 PM IST
5,1st T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Punjab Cricket Association IS Bindra Stadium, ...",20 SEP 2022,7:30 PM IST
6,2nd T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Vidarbha Cricket Association Stadium, Nagpur",23 SEP 2022,7:30 PM IST
7,3rd T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Rajiv Gandhi International Stadium, Hyderabad",25 SEP 2022,7:30 PM IST

In [4]:
# Q3 Solution:

# defining a 'User-Agent' and 'Accept-Language' for our requests.
HEADERS = ({'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0',
            'Accept-Language': 'en-US, en;q=0.5'})

# defining the lists to be used.
names=[]
descriptions=[]

# defining the function for getting the target data.
def guru99_Selenium_Exceptions(url):
    
    r= requests.get(url,headers=HEADERS)     # sending request to the target website.
    soup=bs(r.content)                       # getting the parsed content from which we will extract our data.

    link_data=soup.find("a",title="Selenium",href=True)       # getting the link-data to "Selenium" page using tag and title.

    r= requests.get(url+link_data['href'], headers=HEADERS)   # sending request to the "Selenium" page.
    soup= bs(r.content)                                       # getting the parsed content
    
    # getting the link-data to "Selenium Exception Handling" page using tag and title.
    link_data= soup.find("a",title="Selenium Exception Handling (Common Exceptions List)",href=True)

    r= requests.get(url+link_data['href'], headers=HEADERS)   # sending request to the "Selenium Exception Handling" page.
    soup= bs(r.content)                                       # getting the parsed content
    
    # finding the webelement contaning our target table of "Selenium Exception" and getting the text data.
    data= soup.find("table",class_="table table-striped").text  
    contents=data.strip().split("\n\n\n")                           
    for i in contents[1:]:
        elements= i.split("\n")                   # processing and extracting the relevant data into respective lists.
        names.append(elements[0])
        descriptions.append(elements[1])

    # the final dataframe.
    results= pd.DataFrame({"Name":names,
                           "Description":descriptions
                          })
    return results

url= "https://www.guru99.com"           # mentioning the url to scrap data from.
df= guru99_Selenium_Exceptions(url)     # calling the function and saving the final dataframe.
df

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [5]:
# Q4 Solution:

# defining the lists to be used.
rank=[]
state=[]
gsdp_19_20=[]
gsdp_18_19=[]
share_18_19=[]
gdp=[]

# defining the function for getting the target data.
def Indian_States_GDP(url):
    
    driver.get(url)     # connecting to the target website.
    
    # using the explicit wait method till the "Economy" button gets loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]")))
    # clicking the "Economy" button.
    economy_btn= driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]").click()
    
    # using the explicit wait method till the "India" button gets loaded in the dropdown menu.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")))
    # finding the webelement for "India" button.
    india_btn= driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
    link= india_btn.get_attribute("href")     # getting the link.
    
    try:
        driver.get(link)        # connecting to the "India" page of statisticstimes.
    except WebDriverException:
        pass
    
    try:
        # using the explicit wait method till the "GDP of Indian States" button is loaded.
        wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")))
        # clicking the button.
        states_btn= driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a").click()
    except WebDriverException:
        pass

    try:
        # using the explicit wait method till the desired data is loaded.
        wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"//div[@id='table_id_wrapper']")))
        # finding the webelement containing our target data.
        data= driver.find_element(By.XPATH,"//div[@id='table_id_wrapper']")
    except WebDriverException:
        pass
    
    components= data.text.strip().split("\n")       # splitting the text data based on newline character.
    for i in components[3:]:
        if i==components[-1]:
            pass
        else:        
            elements=i.split(" ")                   # processing and extracting the relevant data into respective lists.
            elements.pop()
            elements.pop()
            rank.append(elements.pop(0))
            gdp.append(elements.pop())
            share_18_19.append(elements.pop())
            gsdp_18_19.append(elements.pop())
            gsdp_19_20.append(elements.pop())
            state.append(" ".join(elements))

    # the final dataframe.
    results= pd.DataFrame({"Rank":rank,
                           "State":state, 
                           "GSDP(19-20)(Cr INR)":gsdp_19_20, 
                           "GSDP(18-19)(Cr INR)":gsdp_18_19,
                           "Share(18-19)":share_18_19,
                           "GDP($B)":gdp
                            })
    return results

url="https://www.statisticstimes.com/"         # mentioning the url to scrap data from.
driver= webdriver.Chrome("chromedriver.exe")   # connecting to the webdriver.
df= Indian_States_GDP(url)                     # calling the function and saving the final dataframe.

driver.close()         # closing the webdriver.
df

,Rank,State,GSDP(19-20)(Cr INR),GSDP(18-19)(Cr INR),Share(18-19),GDP($B)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [6]:
# Q5 Solution:

# defining the lists to be used.
titles=[]
descriptions=[]
contributors=[]
languages=[]

# defining the function for getting the target data.
def Git_Repos(url):
    
    driver.get(url)     # connecting to the target website.

    # using the explicit wait method till the "Explore" button gets loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details")))
    # clicking on the "Explore" button.
    explore_btn= driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details").click()

    # using the explicit wait method till the "Trending" button gets loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")))
    # getting the webelement for the "Trending" button.
    trending_btn= driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
    link= trending_btn.get_attribute('href')   # saving the link to the "Trending" page.
    
    r= requests.get(link)         # sending request to the "Trending" page.
    soup=bs(r.content)            # getting the parsed content from which we will extract our data.               

    data= soup.find_all("article",class_="Box-row")     # finding the webelements for the different repositories.
    
    # running a for loop over each repository webelement.
    for i in data:
        repo_title_data= i.find("h1")                      
        link_data= repo_title_data.find("a",href=True)            # getting the link to the page of that repository.

        r= requests.get("https://github.com"+link_data['href'])   # sending the request to the page.
        soup_new= bs(r.content)                                   # getting the parsed content.

        # finding the title data and extracting it to a list.
        title_data= soup_new.find("strong",class_="mr-2 flex-self-stretch")    
        titles.append(title_data.text.strip())

        # getting the description data and extracting it to a list.
        description_data=soup_new.find("p",class_="f4 my-3")       
        try:
            descriptions.append(description_data.text.strip())
        except AttributeError:
            descriptions.append("-")         # in case of missing data "-" is appended.                            

        # getting the no. of contributors data and extracting it to a list.
        contributors_data= soup_new.find_all("h2",class_="h4 mb-3")     
        for i in contributors_data:
            element=i.text.strip()
            check= element.find("Contributors")
            if check!=(-1):
                contributors.append(element.split("Contributors")[-1].strip())
                break
            elif i==contributors_data[-1]:
                contributors.append("-")
            else:
                continue
        
        # getting the languages-used data and extracting it to a list.
        languages_data= soup_new.find_all("div",class_="BorderGrid-cell")   
        for i in languages_data:
            element=i.text.strip()
            check= element.find("Languages")
            if check!=(-1):
                languages_list=[]
                x= element.split("Languages")[-1].strip().split("\n\n\n\n\n\n\n\n")
                for j in x:
                    languages_list.append(j.split("\n")[0])
                languages_string=",".join(languages_list)
                languages.append(languages_string)
                break
            elif i==languages_data[-1]:
                languages.append("-")
            else:
                continue

    # the final dataframe
    results= pd.DataFrame({"Title":titles,
                           "Description":descriptions, 
                           "Contributors Count":contributors, 
                           "Language Used":languages
                           })
    return results

url="https://github.com"         # mentioning the url to scrap data from.
driver= webdriver.Chrome("chromedriver.exe")       # connecting to the webdriver.
df= Git_Repos(url)          # calling the function and saving the final dataframe.

driver.close()      # closing the webdriver.
df

,Title,Description,Contributors Count,Language Used
0,cmdk,"Fast, unstyled command menu React component.",6,"TypeScript,SCSS,Other"
1,Python,All Algorithms implemented in Python,826,Python
2,system-design-resources,These are the best resources for System Design...,5,-
3,mev_bundle_generator,A MEV bundle generator written in Rust,-,"Rust,Solidity"
4,dotfiles-public,My personal dotfiles,7,"Lua,Shell,PowerShell"
5,graphql-engine,"Blazing fast, instant realtime GraphQL APIs on...",454,"Haskell,TypeScript,JavaScript,Go,Python,CSS,Other"
6,applied-ml,📚 Papers & tech blogs by companies sharing the...,38,-
7,MHDDoS,"Best DDoS Attack Script Python3, (Cyber / DDos...",26,"Python,Dockerfile"
8,unblob,Extract files from any kind of container formats,10,"Python,Nix,Other"
9,TamperingSyscalls,-,2,"C++,Python"
10,coding-interview-university,A complete computer science study plan to beco...,256,-
11,AFFiNE,There can be more than Notion and Miro. Affine...,16,"TypeScript,JavaScript,CSS,HTML,Shell,SCSS"
12,paper2gui,Convert AI papers to GUI，Make it easy and conv...,-,Jupyter Notebook
13,30-Days-Of-React,30 Days of React challenge is a step by step g...,8,"JavaScript,HTML,Other"
14,duckdb,DuckDB is an in-process SQL OLAP Database Mana...,143,"C++,C,Python,JavaScript,Julia,Java,Other"
15,minirust,"A precise specification for ""Rust lite / MIR p...",5,-
16,datahub,The Metadata Platform for the Modern Data Stack,259,"Java,Python,TypeScript,JavaScript,Shell,Docker..."
17,qlib,Qlib is an AI-oriented quantitative investment...,97,"Python,Cython"
18,annotated_deep_learning_paper_implementations,🧑‍🏫 50! Implementations/tutorials of deep lear...,13,"Jupyter Notebook,Python"
19,iptv,Collection of publicly available IPTV channels...,182,"JavaScript,Shell"
20,wechat-assistant-pro,智能微秘书客户端，搭配,-,"JavaScript,Dockerfile"
21,airplay2-receiver,AirPlay 2 Receiver - Python implementation,13,"Python,Other"
22,cs-video-courses,List of Computer Science courses with video le...,69,-
23,astro,Build faster websites with Astro's next-gen is...,298,"TypeScript,JavaScript,Astro,Vue,Svelte,CSS,Other"
24,fiber,⚡️ Express inspired web framework written in Go,236,Go

In [7]:
# Q6 Solution:

# defining the lists to be used.
name=[]
artist=[]
lw_rank=[]
pk_rank=[]
wks_onbd=[]

# defining the function for getting the target data.
def Billboard_100(url):
    
    try:
        driver.get(url)         # connecting to the target website.
    except WebDriverException:
        pass

    time.sleep(2)

    try:
        # using the explicit wait method till the "Charts" button gets loaded.
        wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a")))
        # clicking on the "Charts" button.
        charts_btn= driver.find_element(By.XPATH,"/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a").click()
    except WebDriverException:
        pass

    time.sleep(2)

    try:
        # using the explicit wait method till the "Hot 100" button gets loaded.
        wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[3]/header/div[2]/div/nav/ul/li[1]/a")))
        # finding the webelement for the "Hot 100" button.
        hot_100_btn= driver.find_element(By.XPATH,"/html/body/div[3]/header/div[2]/div/nav/ul/li[1]/a")
        link= hot_100_btn.get_attribute("href")   # getting the link to the "Hot 100" page.
        hot_100_btn.click()    # clicking on the "Hot 100" button.
    except WebDriverException:
        pass

    time.sleep(2)

    try:
        r= requests.get(driver.current_url)      # sending request to the target page.
    except WebDriverException:
        pass

    soup= bs(r.content)        # getting the parsed content.
    
    # finding the webelements containing the songs data.
    data= soup.find_all("div",class_="o-chart-results-list-row-container")  

    # processing each song webelement and extracting the relevant data into respective lists. 
    for i in data:
        song_data= i.find("li",class_="lrv-u-width-100p").text.strip().replace("\n","").replace("\t\t\t\t\t","/").replace("\t\t","/").split("/")
        name.append(song_data[0])
        artist.append(song_data[1])
        wks_onbd.append(song_data.pop())
        pk_rank.append(song_data.pop())
        lw_rank.append(song_data.pop())

    # the final dataframe.
    results= pd.DataFrame({"Song Name":name,
                           "Artist":artist, 
                           "Last Week Rank":lw_rank, 
                           "Peak Rank":pk_rank,
                           "Weeks on chart":wks_onbd
                           })
    
    return results


url="https://www.billboard.com"                  # mentioning the url to scrap data from.
driver= webdriver.Chrome("chromedriver.exe")     # connecting to the webdriver.
df= Billboard_100(url)            # calling the function and saving the final dataframe.

driver.close()        # closing the webdriver.
df

,Song Name,Artist,Last Week Rank,Peak Rank,Weeks on chart
0,Break My Soul,Beyonce,6,1,7
1,About Damn Time,Lizzo,1,1,16
2,As It Was,Harry Styles,2,1,18
3,Running Up That Hill (A Deal With God),Kate Bush,3,3,30
4,Wait For U,Future Featuring Drake & Tems,5,1,14
...,...,...,...,...,...
95,Until I Found You,Stephen Sanchez,88,88,5
96,Un Ratito,Bad Bunny,93,16,13
97,Best Thing Since Backroads,Jake Owen,72,72,4
98,La Corriente,Bad Bunny & Tony Dize,100,32,10
99,"Bzrp Music Sessions, Vol. 52",Bizarrap & Quevedo,98,98,2

In [8]:
# Q7 Solution:

# defining the lists to be used.
name=[]
designation=[]
company=[]
skills=[]
location=[] 

# defining the function for getting the target data.
def Naukri_Recruiters(url):
    
    driver.get(url)            # connecting to the target website.
    driver.maximize_window()   # maximizing the driver window

    time.sleep(1)

    # using the explicit wait method till the "Jobs" button is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"//li[@class='mActive Jobs']")))
    # clicking the "Jobs" button.
    jobs_btn= driver.find_element(By.XPATH,"//li[@class='mActive Jobs']").click()
    
    driver.switch_to.window(driver.window_handles[1])    # switching the driver's current window.

    # using the explicit wait method till the "Recruiters" button is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[1]/div/ul/li[2]/a/div")))
    # clicking the "Recruiters" button.
    recruiter_btn= driver.find_element(By.XPATH,"/html/body/div[1]/div/ul/li[2]/a/div").click()

    driver.switch_to.window(driver.window_handles[2])    # switching the driver's current window.

    # using the explicit wait method till the search-bar is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"//div[@id='skill']")))
    # clicking on the search-bar.
    search_bar= driver.find_element(By.XPATH,"//div[@id='skill']").click()

    # using the explicit wait method till the input element of search-bar is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input")))
    # sending the required keys to the search field. 
    driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input").send_keys("Data Science")

    # using the explicit wait method till the "Search" button is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button")))
    # clicking on the "Search" button.
    search_bar= driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button").click()

    time.sleep(2)

    # using the explicit wait method till the webelements with recruiters data is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"//div[@class='recInfo']")))
    rectr_data= driver.find_elements(By.XPATH,"//div[@class='recInfo']")     # finding the webelements with recruiters data.

    # processing each recruiter's webelement and extracting the relevant data into respective lists.
    for i in rectr_data:
        # finding the elements for name and company data and extracting the text data into respective lists.
        name_company_data= i.find_elements(By.XPATH,".//a[@class='ellipsis']")
        name.append(name_company_data[0].text)
        company.append(name_company_data[1].text)

        # finding the element for designation data and extracting the text data into a list.
        try:
            dsgn_data= i.find_element(By.XPATH,".//span[@class='ellipsis clr']")
            designation.append(dsgn_data.text)
        except NoSuchElementException:
            designation.append("-")        # append "-" if data not available.

        # finding the element for location data and extracting the text data into a list.
        try:
            loctn_data=i.find_element(By.XPATH,".//small[@class='ellipsis']")
            location.append(loctn_data.text)     
        except NoSuchElementException:
            location.append("-")           # append "-" if data not available.

        # finding the element for skills data and extracting the text data into a list.
        try:
            skills_data= i.find_element(By.XPATH,".//div[@class='hireSec highlightable']")
            skills.append(skills_data.text)
        except NoSuchElementException:
            skills.append("-")             # append "-" if data not available.

    # the final dataframe
    results= pd.DataFrame({"Recruiter Name":name,
                           "Designation":designation, 
                           "Company":company, 
                           "Skills hiring for":skills,
                           "Location": location
                          })

    return results

url="https://www.naukri.com/"                  # mentioning the url to scrap data from.           
driver= webdriver.Chrome("chromedriver.exe")   # connecting to the webdriver.
df= Naukri_Recruiters(url)       # calling the function and saving the final dataframe.

driver.quit()        # closing the webdriver.
df

,Recruiter Name,Designation,Company,Skills hiring for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",-
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
34,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",-
49,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,Ghaziabad

In [9]:
# Q8 Solution:

# defining the lists to be used.
name=[]
author=[]
vol_sold=[]
pub=[]
genre=[]

# defining the function for getting the target data.
def Books(url):
    
    r= requests.get(url)      # sending request to the target page.
    soup= bs(r.content)       # getting the parsed content.

    table_data= soup.find("table",class_="in-article sortable")   # getting the webelement for "Data summary" table.
    data= table_data.find_all("tr")           # getting the webelements containing the data about books.
    
    # processing each book webelement and extracting the relevant data into respective lists. 
    for i in data[2:]:
        elements= i.text.strip().split(" \n ")
        genre.append(elements.pop())
        pub.append(elements.pop())
        vol_sold.append(elements.pop())
        author.append(elements.pop())
        name.append(elements.pop())

    # the final dataframe
    results= pd.DataFrame({"Book Name":name,
                           "Author":author, 
                           "Volume Sales":vol_sold, 
                           "Publisher":pub,
                           "Genre":genre
                           })
    return results

# mentioning the target url.
url="https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
df= Books(url)    # calling the function and saving the final dataframe.
df

,Book Name,Author,Volume Sales,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [10]:
# Q9 Solution:

# defining the lists to be used.
name=[]
yr_span=[]
genre=[]
runtime=[]
rating=[]
votes=[]

# defining the function for getting the target data.
def IMDB_Series(url):
    
    r= requests.get(url)       # sending request to the target page.
    soup= bs(r.content)        # getting the parsed content.

    # finding the webelements containing the data about tv-series.
    data= soup.find_all("div",class_='lister-item-content')
    # processing each tv-series webelement and extracting the relevant data into respective lists.
    for i in data:
        elements= i.text.strip().split("|")
        name.append(elements[0].strip().split("\n")[1])
        yr_span.append(elements[0].strip().split("\n")[2])    
        runtime.append(i.find("span",class_="runtime").text.strip())
        genre.append(i.find("span",class_="genre").text.strip())
        votes.append(i.text.strip().split("\n")[-1])
        rating.append(i.find("span",class_="ipl-rating-star__rating").text)

    # the final dataframe
    results= pd.DataFrame({"Name":name,
                           "Year span":yr_span, 
                           "Genre":genre, 
                           "Runtime":runtime,
                           "Rating":rating,
                           "Votes":votes
                           })
    return results

url="https://www.imdb.com/list/ls095964455/"       # mentioning the url to scrap data from.  
df= IMDB_Series(url)           # calling the function and saving the final dataframe.
df

,Name,Year span,Genre,Runtime,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,021,662"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,118,305"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"959,888"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"286,957"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"246,556"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,269"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,169"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"193,425"
98,Scream,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,808"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"233,417"

In [11]:
# Q10 Solution:

# defining the lists to be used.
names=[]
type_=[]
task=[]
attr_type=[]
no_inst=[]
no_attr=[]
year=[]

# defining the function for getting the target data.
def UCI_Databases(url):
    
    driver.get(url)      # connecting to the target website.
    time.sleep(1)

    # using the explicit wait method till the "View ALL Data Sets" button is loaded.
    wait= WebDriverWait(driver,10).until(EC.presence_of_element_located((By.XPATH,"/html/body/table[1]/tbody/tr/td[2]/span[2]/a")))
    # clicking on the "View ALL Data Sets" button.
    driver.find_element(By.XPATH,"/html/body/table[1]/tbody/tr/td[2]/span[2]/a").click()

    time.sleep(3)

    r= requests.get(driver.current_url)     # sending request to the webdriver's current page.  
    soup= bs(r.content,"html.parser")       # getting the parsed content.

    # finding the webelements for the different tables in the page.
    tables_data=soup.find_all("table")
    # choosing the webelement having the table of datasets and then finding the webelements containing the info about various datasets. 
    data= tables_data[1].find_all("tr")     
    
    # processing each dataset-info webelement and extracting the relevant data into respective lists.
    for i in data[18::2]:
        elements= i.find_all("p",class_="normal")
        names.append(elements[0].text.strip())
        type_.append(elements[1].text.strip())
        task.append(elements[2].text.strip())
        attr_type.append(elements[3].text.strip())
        no_inst.append(elements[4].text.strip())
        no_attr.append(elements[5].text.strip())
        year.append(elements[6].text.strip())

    # the final dataframe
    results= pd.DataFrame({"Dataset Name":names,
                           "Data Type":type_, 
                           "Task":task, 
                           "Attribute Type":attr_type,
                           "No. of instances":no_inst,
                           "No. of attributes":no_attr,
                           "Year": year
                           })
    return results
    
url="https://archive.ics.uci.edu/"            # mentioning the url to scrap data from.   
driver= webdriver.Chrome("chromedriver.exe")  # connecting to the webdriver.
df= UCI_Databases(url)        # calling the function and saving the final dataframe.

driver.close()          # closing the webdriver.
df

Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

,Dataset Name,Data Type,Task,Attribute Type,No. of instances,No. of attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021